/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ParticuliersRouteImport } from './routes/particuliers'
import { Route as MethodeRouteImport } from './routes/methode'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as EcolesRouteImport } from './routes/ecoles'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as BlogTempsApprentissageRouteImport } from './routes/blog.temps-apprentissage'
import { Route as AuthEcoleRouteImport } from './routes/auth.ecole'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated.app.index'
import { Route as AuthenticatedAppTrainRouteImport } from './routes/_authenticated.app.train'
import { Route as AuthenticatedAppExamRouteImport } from './routes/_authenticated.app.exam'
import { Route as AuthenticatedAppEcoleRouteImport } from './routes/_authenticated.app.ecole'
import { Route as AuthenticatedAppClassesRouteImport } from './routes/_authenticated.app.classes'
import { Route as AuthenticatedAppCertificationRouteImport } from './routes/_authenticated.app.certification'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticuliersRoute = ParticuliersRouteImport.update({
  id: '/particuliers',
  path: '/particuliers',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodeRoute = MethodeRouteImport.update({
  id: '/methode',
  path: '/methode',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EcolesRoute = EcolesRouteImport.update({
  id: '/ecoles',
  path: '/ecoles',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTempsApprentissageRoute = BlogTempsApprentissageRouteImport.update({
  id: '/blog/temps-apprentissage',
  path: '/blog/temps-apprentissage',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthEcoleRoute = AuthEcoleRouteImport.update({
  id: '/auth/ecole',
  path: '/auth/ecole',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppTrainRoute = AuthenticatedAppTrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppExamRoute = AuthenticatedAppExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppEcoleRoute = AuthenticatedAppEcoleRouteImport.update({
  id: '/ecole',
  path: '/ecole',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppClassesRoute = AuthenticatedAppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCertificationRoute =
  AuthenticatedAppCertificationRouteImport.update({
    id: '/certification',
    path: '/certification',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ecoles': typeof EcolesRoute
  '/guide': typeof GuideRoute
  '/methode': typeof MethodeRoute
  '/particuliers': typeof ParticuliersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/ecole': typeof AuthEcoleRoute
  '/blog/temps-apprentissage': typeof BlogTempsApprentissageRoute
  '/auth/': typeof AuthIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/certification': typeof AuthenticatedAppCertificationRoute
  '/app/classes': typeof AuthenticatedAppClassesRoute
  '/app/ecole': typeof AuthenticatedAppEcoleRoute
  '/app/exam': typeof AuthenticatedAppExamRoute
  '/app/train': typeof AuthenticatedAppTrainRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/ecoles': typeof EcolesRoute
  '/guide': typeof GuideRoute
  '/methode': typeof MethodeRoute
  '/particuliers': typeof ParticuliersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/auth/ecole': typeof AuthEcoleRoute
  '/blog/temps-apprentissage': typeof BlogTempsApprentissageRoute
  '/auth': typeof AuthIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRoute
  '/app/certification': typeof AuthenticatedAppCertificationRoute
  '/app/classes': typeof AuthenticatedAppClassesRoute
  '/app/ecole': typeof AuthenticatedAppEcoleRoute
  '/app/exam': typeof AuthenticatedAppExamRoute
  '/app/train': typeof AuthenticatedAppTrainRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/contact': typeof ContactRoute
  '/ecoles': typeof EcolesRoute
  '/guide': typeof GuideRoute
  '/methode': typeof MethodeRoute
  '/particuliers': typeof ParticuliersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/auth/ecole': typeof AuthEcoleRoute
  '/blog/temps-apprentissage': typeof BlogTempsApprentissageRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRoute
  '/_authenticated/app/certification': typeof AuthenticatedAppCertificationRoute
  '/_authenticated/app/classes': typeof AuthenticatedAppClassesRoute
  '/_authenticated/app/ecole': typeof AuthenticatedAppEcoleRoute
  '/_authenticated/app/exam': typeof AuthenticatedAppExamRoute
  '/_authenticated/app/train': typeof AuthenticatedAppTrainRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/ecoles'
    | '/guide'
    | '/methode'
    | '/particuliers'
    | '/sitemap.xml'
    | '/tarifs'
    | '/app'
    | '/auth/ecole'
    | '/blog/temps-apprentissage'
    | '/auth/'
    | '/app/admin'
    | '/app/certification'
    | '/app/classes'
    | '/app/ecole'
    | '/app/exam'
    | '/app/train'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/ecoles'
    | '/guide'
    | '/methode'
    | '/particuliers'
    | '/sitemap.xml'
    | '/tarifs'
    | '/auth/ecole'
    | '/blog/temps-apprentissage'
    | '/auth'
    | '/app/admin'
    | '/app/certification'
    | '/app/classes'
    | '/app/ecole'
    | '/app/exam'
    | '/app/train'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/contact'
    | '/ecoles'
    | '/guide'
    | '/methode'
    | '/particuliers'
    | '/sitemap.xml'
    | '/tarifs'
    | '/_authenticated/app'
    | '/auth/ecole'
    | '/blog/temps-apprentissage'
    | '/auth/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/certification'
    | '/_authenticated/app/classes'
    | '/_authenticated/app/ecole'
    | '/_authenticated/app/exam'
    | '/_authenticated/app/train'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ContactRoute: typeof ContactRoute
  EcolesRoute: typeof EcolesRoute
  GuideRoute: typeof GuideRoute
  MethodeRoute: typeof MethodeRoute
  ParticuliersRoute: typeof ParticuliersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  AuthEcoleRoute: typeof AuthEcoleRoute
  BlogTempsApprentissageRoute: typeof BlogTempsApprentissageRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/particuliers': {
      id: '/particuliers'
      path: '/particuliers'
      fullPath: '/particuliers'
      preLoaderRoute: typeof ParticuliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methode': {
      id: '/methode'
      path: '/methode'
      fullPath: '/methode'
      preLoaderRoute: typeof MethodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecoles': {
      id: '/ecoles'
      path: '/ecoles'
      fullPath: '/ecoles'
      preLoaderRoute: typeof EcolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/temps-apprentissage': {
      id: '/blog/temps-apprentissage'
      path: '/blog/temps-apprentissage'
      fullPath: '/blog/temps-apprentissage'
      preLoaderRoute: typeof BlogTempsApprentissageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ecole': {
      id: '/auth/ecole'
      path: '/auth/ecole'
      fullPath: '/auth/ecole'
      preLoaderRoute: typeof AuthEcoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/train': {
      id: '/_authenticated/app/train'
      path: '/train'
      fullPath: '/app/train'
      preLoaderRoute: typeof AuthenticatedAppTrainRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/exam': {
      id: '/_authenticated/app/exam'
      path: '/exam'
      fullPath: '/app/exam'
      preLoaderRoute: typeof AuthenticatedAppExamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ecole': {
      id: '/_authenticated/app/ecole'
      path: '/ecole'
      fullPath: '/app/ecole'
      preLoaderRoute: typeof AuthenticatedAppEcoleRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/classes': {
      id: '/_authenticated/app/classes'
      path: '/classes'
      fullPath: '/app/classes'
      preLoaderRoute: typeof AuthenticatedAppClassesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/certification': {
      id: '/_authenticated/app/certification'
      path: '/certification'
      fullPath: '/app/certification'
      preLoaderRoute: typeof AuthenticatedAppCertificationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRoute
  AuthenticatedAppCertificationRoute: typeof AuthenticatedAppCertificationRoute
  AuthenticatedAppClassesRoute: typeof AuthenticatedAppClassesRoute
  AuthenticatedAppEcoleRoute: typeof AuthenticatedAppEcoleRoute
  AuthenticatedAppExamRoute: typeof AuthenticatedAppExamRoute
  AuthenticatedAppTrainRoute: typeof AuthenticatedAppTrainRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRoute,
  AuthenticatedAppCertificationRoute: AuthenticatedAppCertificationRoute,
  AuthenticatedAppClassesRoute: AuthenticatedAppClassesRoute,
  AuthenticatedAppEcoleRoute: AuthenticatedAppEcoleRoute,
  AuthenticatedAppExamRoute: AuthenticatedAppExamRoute,
  AuthenticatedAppTrainRoute: AuthenticatedAppTrainRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ContactRoute: ContactRoute,
  EcolesRoute: EcolesRoute,
  GuideRoute: GuideRoute,
  MethodeRoute: MethodeRoute,
  ParticuliersRoute: ParticuliersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  AuthEcoleRoute: AuthEcoleRoute,
  BlogTempsApprentissageRoute: BlogTempsApprentissageRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
